FROM  linuxserver/ffmpeg:version-8.0-cli

LABEL authors="JankinWu"

# 设置 UTF-8 环境
ENV LANG=C.UTF-8
ENV LC_ALL=C.UTF-8
ENV LANGUAGE=C.UTF-8

# 更新包列表并安装 OpenJDK 17
RUN apt update && \
    apt install -y openjdk-17-jdk && \
    apt install kmod && \
    rm -rf /var/lib/apt/lists/*

COPY build/libs/*.jar /app/app.jar

VOLUME '/app/logs'

WORKDIR /app

EXPOSE 8080

# 设置时区为 Asia/Shanghai
ENV TZ=Asia/Shanghai

# 设置容器的时区
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

ENV SPRING_PROFILES_ACTIVE="release"

ENTRYPOINT ["java", "-jar", "app.jar"]