server:
  port: 8080
spring:
  application.name: fntv-desktop-backend
  datasource:
    url: jdbc:h2:file:./fntv
    driver-class-name: org.h2.Driver
    username: root
    password: fntv2025
    h2:
      console:
        # h2???????????????????
        path: /h2-console
        enabled: true
logging:
  # logback.xml???????
  config: classpath:logback-spring.xml
  level:
    root: INFO

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    #??SQL??
    #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    ##????
    map-underscore-to-camel-case: true